services:
    local-jwks-server:
        image: ghcr.io/murar8/local-jwks-server:latest
        user: ${MY_UID}:${MY_GID}
        volumes:
            # [OPTIONAL] Must contain a private key in PEM format.
            # If no private key file is provided the server will generate
            # a random key upon startup based on the provided configuration.
            # The server conguration must match the private key format.
            - ./rootCA.key:/etc/local-jwks-server/key.pem:ro
        ports:
            - 8080:8080
        # [OPTIONAL] Healthcheck command is configured by default.
        healthcheck:
            retries: 10
