/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/layout/AppBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CodeLine: typeof import('./src/components/common/CodeLine.vue')['default']
    DataList: typeof import('./src/components/common/DataList.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    GreenionLogo: typeof import('./src/components/icons/GreenionLogo.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MachineListItem: typeof import('./src/components/machines/MachineListItem.vue')['default']
    MachineSideView: typeof import('./src/components/machines/MachineSideView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionListItem: typeof import('./src/components/sessions/SessionListItem.vue')['default']
    SessionSideView: typeof import('./src/components/sessions/SessionSideView.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
