# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

FROM node:18-bullseye

ARG USERNAME=anonymous
ARG UID=$USER_UID
ARG GID=$USER_GID

# Use production node environment by default.
ENV NODE_ENV development
ENV PORT 3001

RUN groupadd -g "$GID" -o "$USERNAME"
RUN useradd -m -u "$UID" -g "$GID" -o -s "/bin/bash" "$USERNAME" --no-log-init

WORKDIR /usr/src/app

# Run the application as a non-root user.
USER $USERNAME



# Expose the port that the application listens on.
EXPOSE 3001
# Force yarn to install arm64 and linux package when running on other platform (macOS)
# Run the application.
CMD yarn install --arch=arm64 --platform=linux && yarn dev --host
