[server_auth_config]
cert_file = "certs/cert.pem"
private_key_file = "certs/key.pem"
jwks_url = "http://localhost:8080/.well-known/jwks.json"

[server_network_config]
server_port = 9447
server_listening_ip = "0.0.0.0"

[sanzu_server_launch_config]
sanzu_server_external_startup = true
sanzu_server_port = 1122

